#!/usr/bin/env bash


################
### Symlinks ###
################

printf '\n\e[36mCreating symbolic links...\e[0m\n'

# dotfiles
files=(
	bash/bash_profile
	bash/bashrc
	gitconfig
	latexmkrc
	zsh/zshrc
	omp-themes
)

for file in "${files[@]}"; do 
	ln -snfv "$PWD/$file" "$HOME/.${file##*/}"
done

mkdir -p "$HOME/.config"  # create .config if it doesn't exist

# Neovim
ln -snfv "$PWD/nvim" "$HOME/.config/nvim"

# Fastfetch
ln -snfv "$PWD/fastfetch" "$HOME/.config/fastfetch"


printf '\n\e[32mInstallation complete.\e[0m\n'

